dist: trusty
sudo: false

language: bash

env:
  - PASS_VERSION=1.7.2
  - PASS_VERSION=master

addons:
  apt:
    packages:
      - cabal-install
      - expect
      - ghc
      - oathtool

before_script:
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-$PASS_VERSION.tar.xz
  - tar -xvf password-store-$PASS_VERSION.tar.xz
  - ln -s password-store-$PASS_VERSION/src/password-store.sh pass
  - if [ ! -f "${HOME}/.cabal/bin/shellcheck" ]; then cabal update; cabal install ShellCheck; fi
  - ln -s "${HOME}/.cabal/bin/shellcheck" shellcheck
  - export PATH=$PATH:.
  - export TEST_OPTS="-v"

install: true

before_cache:
  - rm $HOME/.cabal/logs/build.log

cache:
  directories:
    - $HOME/.cabal

script:
  - make lint
  - cd test && make all

notifications:
  email:
    recipients:
      - tadfisher@gmail.com
    on_success: never
    on_failure: always
