name: CI
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v9
        with:
          nix_version: 2.4
          nix_conf: experimental-features = nix-command flakes
      - name: nix build
        run: nix -L build .#
